# Generated by Django 2.2.1 on 2019-06-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('username', models.CharField(max_length=32)),
                ('language', models.CharField(max_length=16)),
            ],
        ),
    ]
