# Generated by Django 2.2.1 on 2019-07-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='filename',
            field=models.CharField(default='test', max_length=32),
        ),
    ]
